export const GET_ORDER_PIZZA = "GET_ORDER_PIZZA";
export const GET_ORDER_PIZZA_PLUS = "GET_ORDER_PIZZA_PLUS";
export const GET_ORDER_PIZZA_MINUS = "GET_ORDER_PIZZA_MINUS";
export const DELETE_BASKET = "DELETE_BASKET";
export const DELETE_ORDER = "DELETE_ORDER";
export const GET_POSTS = "GET_POSTS";
